export const BTN_CLICK = 'BTN_CLICK'

export const SWITCH_HOME_SETTINGS_MODE_CLICK =
  'SWITCH_HOME_SETTINGS_MODE_CLICK'

export const CLEAR_ALL_HISTORY_CLICK =
  'CLEAR_ALL_HISTORY_CLICK'

export const THEME_MODE_CHANGE = 'THEME_MODE_CHANGE'

export const HISTORY_OUTPUT_CHANGE = 'HISTORY_OUTPUT_CHANGE'
